Add managing with external data, fine-tuning for external data embedders
dllllb/pytorch-lifestream pull request #110
Opened 2023-03-27 12:07 UTC by WhatCanWeDo

2023-04-06 13:53 UTC, FuTSy13 requested changes

2023-04-06 13:53 UTC, FuTSy13 commented on ptls/nn/trx_encoder/scalers.py
 Зачем нужен класс BaseScaler? В качестве базового класса годится BaseEncoder. А все потомки BaseScaler вызывают super().forward(x), вместо чего можно просто писать x.unsqueeze(2).float(). Еще IdentityScaler совпадает по функционалу с BaseScaler.
Предлагаю удалить класс BaseScaler, всех его потомков отнаследовать от BaseEncoder, и заменить x=super().forward(x) на x=x.unsqueeze(2).float()

2023-04-06 14:53 UTC, FuTSy13 commented on ptls/nn/trx_encoder/trx_encoder.py
Зачем импортируется concurrent.futures.process ?

2023-04-06 15:00 UTC, FuTSy13 commented on ptls/nn/trx_encoder/trx_encoder.py
Я вижу много изменений связанных с numeric_values. Кажется, они могут нарушить обратную совместимость. Может стоит вынести все эти изменения в отдельный класс TrxEncoderWithEmbeddings?

2023-04-06 16:42 UTC, WhatCanWeDo commented on ptls/nn/trx_encoder/trx_encoder.py
Забыл почистить 🥴

2023-04-06 16:46 UTC, WhatCanWeDo commented on ptls/nn/trx_encoder/trx_encoder.py
Я старался следить, чтобы изменений не было по логике работы именно с numeric_values + тесты, которые их затрагивают проходят. Если обратная совместимость сохранилась, то не хочется лишних сущностей плодить

2023-04-06 16:50 UTC, FuTSy13 commented on ptls/nn/trx_encoder/trx_encoder.py
Если ты с ptls-experimets работал, можешь запустить все эксперименты например на росбанке, чтобы проверить, что реально ничего не сломалось. Если ты не запускал никогда, я завтра сам проверю

2023-05-11 11:42 UTC, ivkireev86 commented on ptls/nn/trx_encoder/trx_encoder.py
Эксперименты работают

2023-05-11 11:49 UTC, FuTSy13 approved these changes

2023-05-11 11:49 UTC, merged