coles-emb.ipynb - torch downgrage
dllllb/pytorch-lifestream pull request #135
Opened 2023-11-28 10:54 UTC by ivkireev86

2023-12-06 14:46 UTC, FuTSy13 requested changes

2023-12-06 14:46 UTC, FuTSy13 commented on demo/coles-emb.ipynb
Надо у torchaudio снизить версию еще. Выдает ошибку undefined symbol error
```
! {sys.executable} -m pip install -U 'torchaudio<2.0.1'  # downgrade for ptls==0.5.x
```

2023-12-06 14:46 UTC, FuTSy13 commented on demo/coles-pretrained-embeddings.ipynb
Тут поддержка колаба пока не нужна?

2023-12-06 21:21 UTC, ivkireev86 commented on demo/coles-pretrained-embeddings.ipynb
По нормальному - везде нужна.
А еще надо на torch2 перейти.
И демо порефакторить по нормальному.
Предлагаю пока отложить все это

2023-12-07 15:41 UTC, FuTSy13 approved these changes

2023-12-07 15:41 UTC, merged